import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  // repos/ holds vendored third-party source (git subtree): never format it.
  // pnpm-lock.yaml is generated by pnpm.
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    "repos/**",
    "**/pnpm-lock.yaml",
  ],
});
