import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import { parseDotenv, toSecretKey } from "../dist/dotenv.js";
import {
  buildRescuePlan,
  classifyEnvFile,
  countSecrets,
} from "../dist/rescue/scan.js";

const withTree = (files, run) => {
  const root = mkdtempSync(path.join(tmpdir(), "envsec-rescue-"));
  try {
    for (const [relative, content] of Object.entries(files)) {
      const full = path.join(root, relative);
      mkdirSync(path.dirname(full), { recursive: true });
      writeFileSync(full, content);
    }
    run(root);
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
};

test("parses the common dotenv dialect", () => {
  const entries = parseDotenv(
    [
      "# comment",
      "PLAIN=value # inline comment",
      "export EXPORTED=1",
      'DOUBLE="a \\"quoted\\" \\n value"',
      "SINGLE='keep $raw #text'",
      'MULTI="line1',
      'line2"',
      "EMPTY=",
      "not an assignment",
    ].join("\r\n")
  );
  assert.deepEqual(
    entries.map(({ name, value }) => [name, value]),
    [
      ["PLAIN", "value"],
      ["EXPORTED", "1"],
      ["DOUBLE", 'a "quoted" \n value'],
      ["SINGLE", "keep $raw #text"],
      ["MULTI", "line1\nline2"],
      ["EMPTY", ""],
    ]
  );
});

test("ignores a UTF-8 byte order mark", () => {
  const [entry] = parseDotenv("\uFEFFAPI_TOKEN=abc\r\nPORT=1\r\n");
  assert.equal(entry.name, "API_TOKEN");
  assert.equal(entry.value, "abc");
});

test("reads back the escaping written by envsec env-file", () => {
  // env-file writes KEY="value" escaping \\, " and newlines.
  const value = 'a\nb "quoted" back\\slash';
  const escaped = value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\n", "\\n");
  const [entry] = parseDotenv(`MULTI_LINE="${escaped}"\n`);
  assert.equal(entry.value, value);
  assert.equal(toSecretKey(entry.name), "multi.line");
});

test("classifies env files and skips templates", () => {
  assert.deepEqual(classifyEnvFile(".env"), { mode: "dev", precedence: 0 });
  assert.deepEqual(classifyEnvFile(".env.local"), {
    mode: "dev",
    precedence: 1,
  });
  assert.deepEqual(classifyEnvFile(".env.production"), {
    mode: "prod",
    precedence: 2,
  });
  assert.deepEqual(classifyEnvFile(".env.staging.local"), {
    mode: "staging",
    precedence: 3,
  });
  for (const name of [".env.example", ".env.sample", ".env.vault", ".envrc"]) {
    assert.equal(classifyEnvFile(name), null, name);
  }
});

test("groups files by project, layers modes and finds duplicates", () => {
  withTree(
    {
      "client/api/.env": "TOKEN=shared-token-value\n",
      "client/api/package.json": "{}",
      "legacy/api/.env.production": "TOKEN=shared-token-value\n",
      "legacy/api/package.json": "{}",
      "shop/.env": "PORT=3000\nAPI_KEY=abc\nBAD__NAME=x\nEMPTY=\n",
      "shop/.env.example": "PORT=\n",
      "shop/.env.local": "PORT=4000\n",
      "shop/node_modules/dep/.env": "IGNORED=yes\n",
      "shop/package.json": "{}",
    },
    (root) => {
      const plan = buildRescuePlan(root);
      const contexts = plan.projects.flatMap((p) => p.contexts);

      assert.deepEqual(
        contexts.map((c) => c.name),
        ["client-api.dev", "legacy-api.prod", "shop.dev"]
      );
      const shop = contexts.find((c) => c.name === "shop.dev");
      assert.equal(shop.secrets.get("port").value, "4000");
      assert.equal(shop.secrets.get("api.key").value, "abc");
      assert.equal(countSecrets(plan), 4);

      const shopEnv = shop.files.find((f) => f.path.endsWith(".env"));
      assert.deepEqual(shopEnv.invalidNames, ["BAD__NAME"]);
      assert.deepEqual(shopEnv.emptyNames, ["EMPTY"]);

      assert.equal(plan.duplicates.length, 1);
      assert.deepEqual(
        plan.duplicates[0].locations.map((l) => l.context),
        ["client-api.dev", "legacy-api.prod"]
      );
    }
  );
});

test("leaves files generated by envsec env-file alone", () => {
  withTree({ "app/.env": "KEY=value\n" }, (root) => {
    const exported = path.join(root, "app/.env");
    const plan = buildRescuePlan(root, { exportedPaths: new Set([exported]) });
    assert.equal(countSecrets(plan), 0);
    assert.deepEqual(plan.skippedExports, [exported]);
  });
});
